import { StyleSheet } from "react-native";

export default StyleSheet.create({
  background: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  button: {
    width: "25%",
    height: "8%",
    backgroundColor: "navy",
    marginTop: "1%",
  },
  buttonText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
    paddingBottom: "2%",
    paddingTop: "2%",
    textAlign: "center",
    textAlignVertical: "center",
  },
  buttonExit: {
    width: 150,
    padding: 5,
    backgroundColor: "#ff9999",
    borderWidth: 2,
    borderColor: "#ffcccc",
    borderRadius: 15,
    alignSelf: "center",
    margin: "1%",

    marginTop: "-3%",
  },
  buttonTextExit: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 20,
  },
  updateButton: {
    width: 200,
    padding: 2,
    backgroundColor: "#ff9999",
    borderWidth: 2,
    borderColor: "#ffcccc",
    borderRadius: 15,
    alignSelf: "center",
    // margin: 5,
    marginTop: "-6%",
  },
  updateButtonText: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 20,
  },
  endGameText: {
    color: "red",
  },
  submitContainer: {
    flex: 1,
  },
  endContainer: {
    flex: 1,
    flexDirection: "row",
  },
  qContainer: {
    flex: 1,
    flexDirection: "row",
    marginTop: "5%",
    marginBottom: "10%",
  },
  qAnswerText: {
    fontSize: 20,
  },
  holder: {
    height: 60,
    width: 150,
    borderColor: "#7BB5B7",
    borderWidth: 3,
    fontSize: 40,
    textAlign: "center",
  },
  ansholder: {
    height: 60,
    width: 100,
    borderColor: "#7BB5B7",
    borderWidth: 3,
    fontSize: 40,
    textAlign: "center",
  },
  qAnswerContainer: {
    height: 60,
    width: 100,
    borderColor: "#7BB5B7",
    borderWidth: 3,
    fontSize: 40,
    textAlign: "center",
  },
  plus: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 45,
  },
  number: {
    color: "white",
  },
  waitingTitle: {
    textAlign: "center",
    fontSize: 25,
    marginTop: "1%",
    marginBottom: "2%",
    fontWeight: "bold",
    color: "#FFB30F",
  },
  screenTitle: {
    textAlign: "center",
    fontSize: 25,
    margin: 10,
    fontWeight: "bold",
    color: "white",
  },
  textInput: {
    width: 250,
    borderWidth: 1,
    borderColor: "#6DA171",
    padding: 10,
    margin: "0.2%",
  },
  title: {
    color: "#7BB5B7",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 35,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
  subtext: {
    color: "#FFB30F",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
});
