import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  button: {
    width: 250,
    padding: 5,
    backgroundColor: "#8F540E",
    borderWidth: 2,
    borderColor: "#AD8557",
    borderRadius: 15,
    alignSelf: "center",
    margin: 8,
    marginTop: "2%",
  },
  buttonText: {
    color: "white",
    fontSize: 25,
    fontWeight: "bold",
    textAlign: "center",
  },
  container: {
    flex: 1,
    padding: "8%",
    backgroundColor: "#3FC5AB",
    alignItems: "center",
    justifyContent: "center",
  },
  input: {
    width: 300,
    height: 60,
    fontSize: 35,
    fontWeight: "bold",
    borderWidth: 3,
    borderColor: "#96C598",
    padding: 10,
    margin: 5,
  },
  text: {
    textAlign: "center",
    fontSize: 35,
    margin: 10,
    fontWeight: "bold",
    color: "#441196",
  },
  backButton: {
    borderWidth: 1,
    borderColor: "#8FE09B",
    borderRadius: 15,
    padding: 1,
    marginLeft: "-90%",
    marginTop: "-5%",
    marginBottom: "5%",
    width: 110,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
  backButtonText: {
    color: "#8FE09B",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 20,
  },
});
